log_level: DEBUG
Camera:
  ROI:
    start_x: 0
    start_y: 0
    width: 346
    height: 260
  Trigger:
    rising_edge: True
    falling_edge: False
  Filter:
    enable: True
    background_activity_duration: 2000
  Accumulation:
    window_us: 16666
    start_time_offset_us: 0
  width: 346
  height: 260
    
# Anything below is WIP
DMD_TMP:
  channel: TRIG_OUT_2
  source_dmd: A
  edge: rising
  rising_delay_us: timing["rising_delay_us"] # 0
  falling_delay_us: timing["falling_delay_us"] # 20
DMD:
  A:
    usb_id_path: pci-0000:03:00.0-usb-0:1:1.0
    usb_devpath: /usb1/1-1/1-1:1.0/
    xrandr_output: DP-2    
  B:
    usb_id_path: pci-0000:03:00.0-usb-0:8:1.0
    usb_devpath: /usb1/1-8/1-8:1.0/
    xrandr_output: DP-0
  width: 1920
  height: 1080
  offset: [0, 0]
  target_hz: 60
  wake_dp: False
  safe_margin_us: 250.0
  min_exposure_us: 150
  frame_utilization: 1.0
  # constants
  dark_time_us: 0
  bitplanes: 24
  VID: 0x0451
  PID: 0xC900