"""Shared constants for DMD display, LUT timing, and camera runners."""

# --- DMD & DLPC900 Hardware and Timing ---
DEFAULT_HZ = 60
TARGET_HZ = DEFAULT_HZ
BITPLANES = 24
MIN_EXPOSURE_US = 150
INTER_PATTERN_DARK_US = 0
MAX_BINARY_RATE_HZ_DLP6500 = 9523
SAFE_MARGIN_US = 250.0
MAX_MEASURED_VSYNC_DEVIATION_RATIO = 0.25
DEFAULT_SEQUENCE_UTILIZATION = 0.90

# DMD Display resolution
DMD_WIDTH = 1920
DMD_HEIGHT = 1080
DMD_CENTER_X = DMD_WIDTH // 2
DMD_CENTER_Y = DMD_HEIGHT // 2

# DLPC900 USB VID/PID
DLPC900_VID = 0x0451
DLPC900_PID = 0xC900

# Signed int16 ranges
SIGNED_INT16_MIN = -32768
SIGNED_INT16_MAX = 32767

# DLPC900 trigger output edge delay range. The public rising-edge delay keeps
# a fixed 20 us pulse, so its maximum is lower than the raw edge maximum.
TRIGGER_OUT_DELAY_MIN_US = -20
TRIGGER_OUT_DELAY_MAX_US = 20000
TRIGGER_OUT_PULSE_WIDTH_US = 20
TRIGGER_OUT_RISING_DELAY_MIN_US = TRIGGER_OUT_DELAY_MIN_US
TRIGGER_OUT_RISING_DELAY_MAX_US = TRIGGER_OUT_DELAY_MAX_US - TRIGGER_OUT_PULSE_WIDTH_US

# Calibration square defaults
DEFAULT_CALIBRATION_SQUARE_FRACTION = 0.25
MIN_CALIBRATION_SQUARE_PX = 4

# Common runtime defaults
DEFAULT_RUNTIME_SECONDS = 60
DEFAULT_SYNC_CHECK_RUNTIME_SECONDS = 0
DEFAULT_PAIR_CAPTURE_RUNTIME_SECONDS = 999
DEFAULT_PAIRED_STARTUP_LEADER_VSYNCS = 16
DEFAULT_TRIGGER_OUT_2_RISING_DELAY_US = 0
DEFAULT_ABORT_RECOVER_COOLDOWN_S = 8.0

# Paired dot/count/kernel defaults
DEFAULT_DOT_RADIUS_PX = 40
DEFAULT_SYNC_CHECK_DOT_RADIUS_PX = 20
DEFAULT_COUNT_START = 1
DEFAULT_COUNT_END = 100
DEFAULT_SYNC_CHECK_COUNT_END = 5
DEFAULT_SYNC_CHECK_NUMBER_SIZE_PX = 100
DEFAULT_KERNEL_PX = 30
DEFAULT_PAIR_CAPTURE_KERNEL_PX = 129
DEFAULT_KERNEL_LEADER_FRAMES = 3
KERNEL_VARIATION_COUNT = 512
DEFAULT_PREVIEW_FPS = 1.0

# Coarse grid defaults
DEFAULT_COARSE_GRID_SPACING = 75
DEFAULT_COARSE_GRID_THICKNESS = 8
DEFAULT_COARSE_LINE_SPACING = 150
DEFAULT_COARSE_LINE_THICKNESS = 24
DEFAULT_ROUTE_MARKER_SIZE = 168

# --- Dvxplorer camera defaults ---
DVXPLORER_CONTRAST_THRESHOLDS = {
    "verylow": 15,
    "low": 12,
    "high": 6,
    "veryhigh": 3,
    # "default" at 9
}
DVXPLORER_READOUT_FPS_NAMES = {
    "variable": "VARIABLE",
    "variable_5000": "VARIABLE_5000",
    "constant_1000": "CONSTANT_1000",
    "constant_100": "CONSTANT_100",
}

# --- Capture artifact defaults ---
DEFAULT_SYNC_CHECK_CAMERA_FLUSH_READS = 32
DEFAULT_PAIR_CAPTURE_CAMERA_FLUSH_READS = 1
DEFAULT_CAMERA_POST_TRIGGER_EVENT_BATCHES = 0
DEFAULT_MAX_ACCUMULATION_TRIGGERS = KERNEL_VARIATION_COUNT

# --- Local support filter defaults ---
DEFAULT_FILTER_DELTA_T_US = 50_000
DEFAULT_FILTER_WINDOW_PX = 3
DEFAULT_FILTER_THRESHOLD = 2
DEFAULT_FILTER_POLARITY = "same"
