"""Shared runtime constants for DLPC900 Video Pattern Mode."""

# --- DMD & DLPC900 Hardware and Timing ---
DEFAULT_HZ = 60
TARGET_HZ = DEFAULT_HZ
BITPLANES = 24
MIN_EXPOSURE_US = 150
INTER_PATTERN_DARK_US = 0
MAX_BINARY_RATE_HZ_DLP6500 = 9523
SAFE_MARGIN_US = 250.0
MAX_MEASURED_VSYNC_DEVIATION_RATIO = 0.25
DEFAULT_SEQUENCE_UTILIZATION = 0.90

# DMD Display resolution
DMD_WIDTH = 1920
DMD_HEIGHT = 1080

# DLPC900 USB VID/PID
DLPC900_VID = 0x0451
DLPC900_PID = 0xC900

# Signed int16 ranges
SIGNED_INT16_MIN = -32768
SIGNED_INT16_MAX = 32767

# DLPC900 trigger output edge delay range. The public rising-edge delay keeps
# a fixed 20 us pulse, so its maximum is lower than the raw edge maximum.
TRIGGER_OUT_DELAY_MIN_US = -20
TRIGGER_OUT_DELAY_MAX_US = 20000
TRIGGER_OUT_PULSE_WIDTH_US = 20
TRIGGER_OUT_RISING_DELAY_MIN_US = TRIGGER_OUT_DELAY_MIN_US
TRIGGER_OUT_RISING_DELAY_MAX_US = TRIGGER_OUT_DELAY_MAX_US - TRIGGER_OUT_PULSE_WIDTH_US

# --- Pattern Modes defaults ---
NUMBER_SEQUENCE = tuple(range(1, 10))
DEFAULT_NUMBERS_EXPOSURE_US = 500_000

# Calibration square defaults
DEFAULT_CALIBRATION_SQUARE_FRACTION = 0.25
MIN_CALIBRATION_SQUARE_PX = 4

# Coarse grid defaults
DEFAULT_COARSE_GRID_SPACING = 75
DEFAULT_COARSE_GRID_THICKNESS = 8
DEFAULT_COARSE_LINE_SPACING = 150
DEFAULT_COARSE_LINE_THICKNESS = 24
DEFAULT_ROUTE_MARKER_SIZE = 168

# --- Dvxplorer camera defaults ---
DVXPLORER_CONTRAST_THRESHOLDS = {
    "verylow": 15,
    "low": 12,
    "high": 6,
    "veryhigh": 3,
    # "default" at 9
}
DVXPLORER_READOUT_FPS_NAMES = {
    "variable": "VARIABLE",
    "variable_5000": "VARIABLE_5000",
    "constant_1000": "CONSTANT_1000",
    "constant_100": "CONSTANT_100",
}

# --- Local support filter defaults ---
DEFAULT_FILTER_DELTA_T_US = 50_000
DEFAULT_FILTER_WINDOW_PX = 3
DEFAULT_FILTER_THRESHOLD = 2
DEFAULT_FILTER_POLARITY = "same"
