from __future__ import annotations

import argparse
import csv
import shlex
from pathlib import Path

from dmdcontrol.camera import sync_check
from dmdcontrol.camera.capture import flush_stale_batches
from dmdcontrol.camera.runs import create_run_directory
from dmdcontrol.camera.session import (
    close_camera_resources,
    open_camera_writer,
    open_ready_camera_capture,
)

PERSISTENT_CAMERA_FIELDS = [
    "camera_open_method",
    "camera_stream_rearm",
    "camera_shutdown_streams",
    "camera_flush_reads",
    "bias_sensitivity",
    "efps",
]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m dmdcontrol camera sync-sweep",
        description="Run a sync-check manifest in one process with one camera open.",
    )
    parser.add_argument("--manifest", required=True, help="CSV manifest generated by notebook 01.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Create run artifacts without opening hardware.")
    return parser


def _has_value(value) -> bool:
    return value is not None and str(value).strip() not in {"", "None", "none", "nan"}


def _row_sync_check_argv(row: dict[str, str]) -> tuple[list[str], list[str]]:
    explicit = row.get("sync_check_argv", "")
    if explicit.strip():
        argv = shlex.split(explicit)
        return argv, ["python", "-m", "dmdcontrol", "camera", "sync-check", *argv]

    command = row.get("command", "")
    if command.strip():
        tokens = shlex.split(command)
        if tokens and tokens[0].endswith("run_camera_sync_check.sh"):
            return tokens[1:], tokens
        if "sync-check" in tokens:
            return tokens[tokens.index("sync-check") + 1:], tokens
        return tokens, tokens

    raise SystemExit("Manifest rows must include sync_check_argv or command.")


def _load_manifest(path: Path) -> list[tuple[dict[str, str], list[str], list[str], argparse.Namespace]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit(f"Manifest has no rows: {path}")

    parsed = []
    parser = sync_check.build_parser()
    for index, row in enumerate(rows):
        argv, command_argv = _row_sync_check_argv(row)
        args = parser.parse_args(argv)
        args.sweep_manifest = str(path)
        args.sweep_index = int(row["index"]) if _has_value(row.get("index")) else index
        if _has_value(row.get("sweep_id")):
            args.sweep_id = row["sweep_id"]
        if _has_value(row.get("repeat")):
            args.sweep_repeat = int(row["repeat"])
        parsed.append((row, argv, command_argv, args))
    return parsed


def _validate_persistent_camera_args(parsed_rows) -> None:
    first_args = parsed_rows[0][3]
    first = {name: getattr(first_args, name, None) for name in PERSISTENT_CAMERA_FIELDS}
    for row_number, (_, _, _, args) in enumerate(parsed_rows[1:], start=2):
        for name, expected in first.items():
            actual = getattr(args, name, None)
            if actual != expected:
                raise SystemExit(
                    f"Manifest row {row_number} changes --{name.replace('_', '-')} "
                    f"from {expected!r} to {actual!r}; persistent camera settings must not vary.")


def dry_run(parsed_rows) -> int:
    for _, _, command_argv, args in parsed_rows:
        args.dry_run = True
        sync_check.dry_run(args, command_argv=command_argv)
    return 0


def live(parsed_rows) -> int:
    _validate_persistent_camera_args(parsed_rows)
    first_args = parsed_rows[0][3]
    capture = None
    try:
        capture, ready = open_ready_camera_capture(first_args)
        for _, _, command_argv, args in parsed_rows:
            run = create_run_directory("sync-check", args.output_root, timestamp=args.timestamp)
            writer = None
            try:
                flush_stale_batches(
                    capture,
                    reads=args.camera_flush_reads,
                )
                writer = open_camera_writer(run, capture)
                sync_check.live_capture(
                    args,
                    run,
                    capture,
                    writer,
                    ready,
                    command_argv=command_argv)
            finally:
                resources = {"writer": writer}
                writer = None
                close_camera_resources(resources, shutdown_streams=False)
        return 0
    finally:
        resources = {"capture": capture}
        capture = None
        close_camera_resources(
            resources,
            shutdown_streams=first_args.camera_shutdown_streams if parsed_rows else False,
        )


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    manifest_path = Path(args.manifest)
    parsed_rows = _load_manifest(manifest_path)
    if args.dry_run:
        return dry_run(parsed_rows)
    return live(parsed_rows)
