Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "DLPC-Screen" 0 0
EndSection

Section "Monitor"
    Identifier  "DLPC_Monitor"
    HorizSync   30.0 - 100.0
    VertRefresh 50.0 - 130.0
    # Custom 60.000 Hz EXACT timing
    ModeLine    "1920x1080_60_RAW"  138.6528  1920 1968 2000 2080  1080 1083 1088 1111  +HSync -VSync
    Option      "DPMS" "false"
EndSection

Section "Device"
    Identifier  "NVIDIA-DLPC"
    Driver      "nvidia"
    Option      "Monitor-DP-0" "DLPC_Monitor"
    Option      "Monitor-DP-1" "DLPC_Monitor"
    Option      "Monitor-DP-2" "DLPC_Monitor"
    Option      "Monitor-DP-3" "DLPC_Monitor"
    Option      "Monitor-DP-4" "DLPC_Monitor"
    Option      "Monitor-DP-5" "DLPC_Monitor"
    Option      "ModeValidation" "AllowNonEdidModes, NoMaxPClkCheck, NoEdidMaxPClkCheck, NoVertRefreshCheck, NoHorizSyncCheck, NoMaxSizeCheck, NoXServerCheck, NoDFPNativeResolutionCheck, NoVesaModes, NoXServerModes, NoPredefinedModes"
    Option      "ExactModeTimingsDVI" "true"
EndSection

Section "Screen"
    Identifier  "DLPC-Screen"
    Device      "NVIDIA-DLPC"
    Monitor     "DLPC_Monitor"
    DefaultDepth 24
    # Force Xorg to boot directly into this mode with pure RGB 4:4:4
    Option      "MetaModes" "1920x1080_60_RAW +0+0 {ColorSpace=RGB, ColorRange=Full, ForceFullCompositionPipeline=On}"
EndSection
